\documentclass[english,floatsintext,man]{apa6}

\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}

% Table formatting
\usepackage{longtable, booktabs}
\usepackage{lscape}
% \usepackage[counterclockwise]{rotating}   % Landscape page setup for large tables
\usepackage{multirow}		% Table styling
\usepackage{tabularx}		% Control Column width
\usepackage[flushleft]{threeparttable}	% Allows for three part tables with a specified notes section
\usepackage{threeparttablex}            % Lets threeparttable work with longtable

% Create new environments so endfloat can handle them
% \newenvironment{ltable}
%   {\begin{landscape}\begin{center}\begin{threeparttable}}
%   {\end{threeparttable}\end{center}\end{landscape}}

\newenvironment{lltable}
  {\begin{landscape}\begin{center}\begin{ThreePartTable}}
  {\end{ThreePartTable}\end{center}\end{landscape}}




% The following enables adjusting longtable caption width to table width
% Solution found at http://golatex.de/longtable-mit-caption-so-breit-wie-die-tabelle-t15767.html
\makeatletter
\newcommand\LastLTentrywidth{1em}
\newlength\longtablewidth
\setlength{\longtablewidth}{1in}
\newcommand\getlongtablewidth{%
 \begingroup
  \ifcsname LT@\roman{LT@tables}\endcsname
  \global\longtablewidth=0pt
  \renewcommand\LT@entry[2]{\global\advance\longtablewidth by ##2\relax\gdef\LastLTentrywidth{##2}}%
  \@nameuse{LT@\roman{LT@tables}}%
  \fi
\endgroup}


  \usepackage{graphicx}
  \makeatletter
  \def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
  \def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
  \makeatother
  % Scale images if necessary, so that they will not overflow the page
  % margins by default, and it is still possible to overwrite the defaults
  % using explicit options in \includegraphics[width, height, ...]{}
  \setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            pdfauthor={},
            pdftitle={A thorough evaluation of the Language Environment Analysis (LENATM) system},
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=black,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls

\setlength{\parindent}{0pt}
%\setlength{\parskip}{0pt plus 0pt minus 0pt}

\setlength{\emergencystretch}{3em}  % prevent overfull lines

\ifxetex
  \usepackage{polyglossia}
  \setmainlanguage{}
\else
  \usepackage[english]{babel}
\fi

% Manuscript styling
\captionsetup{font=singlespacing,justification=justified}
\usepackage{csquotes}
\usepackage{upgreek}



\usepackage{tikz} % Variable definition to generate author note

% fix for \tightlist problem in pandoc 1.14
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% Essential manuscript parts
  \title{A thorough evaluation of the Language Environment Analysis (LENATM)
system}

  \shorttitle{IN PREP - LENA EVAL}


  \author{many\textsuperscript{1}}

  % \def\affdep{{""}}%
  % \def\affcity{{""}}%

  \affiliation{
    \vspace{0.5cm}
          \textsuperscript{1}   }

  \authornote{
    Correspondence concerning this article should be addressed to many, .
    E-mail:
  }


  \abstract{waiting}
  




\begin{document}

\maketitle

\setcounter{secnumdepth}{0}



\subsubsection{Brief introduction to LENA(R)
products}\label{brief-introduction-to-lenar-products}

\subsubsection{Previous validation work}\label{previous-validation-work}

\subsubsection{Present work}\label{present-work}

\subsection{Methods}\label{methods}

\subsubsection{Corpora}\label{corpora}

\subsubsection{Processing}\label{processing}

\subsubsection{LENA classification
accuracy}\label{lena-classification-accuracy}

\paragraph{Speech and talker segmentation
metrics}\label{speech-and-talker-segmentation-metrics}

\paragraph{Precision and recall}\label{precision-and-recall}

\subsubsection{CVC and CTC evaluation}\label{cvc-and-ctc-evaluation}

\subsubsection{AWC evaluation}\label{awc-evaluation}

\subsection{Results}\label{results}

Before starting, we provide some general observations based on the human
annotation. Silence is extremely common, constituting 79\% of the
frames. In fact, 45\% of clips contained no speech by any of the human
speaker types (according to the human annotators). As for speakers,
female adults make up 11\% of the frames, the child contributes to 4\%
of the frames, whereas male adult voices, other child voices, and
electronic voices are found in only 1\% of the frames each. Overlap
makes up the remaining 3\% of the frames. The following consequences
ensue: if frame-based accuracy is sought, a system that classifies every
frame as silence would be 79\% correct. This is of course not what we
want, but it indicates that systems adapted to this kind of speech
should tend to have low \enquote{false alarm} rates, i.e.~a preference
for being very conservative as to when there is speech. If the system
does say there is speech, then it had better say that this speech comes
from female adults, who provide a great majority of the speech. In
second place, it should be key child. Given that male adults and other
children are rare, a system that makes a lot of mistakes in these
categories may still have a good global performance, because these
categories are extremely rare.

\subsubsection{LENA classification accuracy: False alarms, misses,
confusion}\label{lena-classification-accuracy-false-alarms-misses-confusion}

Our first analysis is based on standard speech technology metrics, which
put errors in the perspective of how much speech there is. That is, if
10 frames are wrong in a file where there are 100 frames with speech,
this is a much smaller problem than if 10 frames are wrong in a file
where there is 1 frame with speech. In other words, these metrics should
be considered relative error metrics. One problem, however, emerges when
there is no speech whatsoever in a given file. In the speech technology
literature, this is never discussed, because most researchers working on
this are basing their analyses on files that have been selected to
contain speech (e.g., recorded in a meeting, or during a phone
conversation). We still wanted to take into account clips with no speech
inside because it is key for our research goals: We need systems that
can deal well with long stretches of silence, because we want to measure
how much speech children hear. Indeed, as mentioned above, 45\% of our
clips had no speech whatsoever. In these cases, the false alarm and
confusion metrics are undefined. It also occurred that there was just a
little speech; in this case, the denominator is very small, and
therefore the ratio for these two metrics ended up being a very large
number. Since the presence of outliers violate a basic assumption of
regression models, and outliers greatly impact means, we declared as NA
any metric that was 2 standard deviations above the mean over all clips.
Please note that this leads to an overestimation of LENA's performance,
because clips where the relative error rate is very high are removed
from consideration. Also, preliminary analyses revealed that performance
was lower when near and far were collapsed together (i.e., CHN and CHF
were mapped onto a single CH category), so the following analyses use
only near speaker categories (i.e., CHN, FAN, MAN, CXN) as well as the
overlap category (OLN), with all other categories mapped as non-speech
(i.e., CHF, CXF, FAF, MAF, NOF, NON, OLF, TVF, SIL). \textbf{For a first
analysis on all files, TVN was also mapped as non-speech; a follow-up
analysis only on ACLEW data segregated TVN such that there were 5
\enquote{speaker} categories: CHN, FAN, MAN, CXN, and TVN.}

LENA's false alarm (i.e., saying that someone was speaking when they
were not) averaged 178\%, whereas the miss rate averaged 24\%. The
confusion rate, as mentioned above, is only calculated for the correctly
detected speech (i.e., not the speech that was missed, which counts
towards the miss rate, nor the speech that was falsely identified, which
is considered in the false alarm). The confusion rate was very low,
averaging 29\%. These three metrics can be added together into a single
\enquote{diarization error rate}; of course, if one of them is NA, then
DER is NA; 0\% of the clips had NA diarization error rate
(\texttt{round(sum(is.na(py\$missed.detection..))/dim(py){[}1{]}*100)}
due to having no speech and 0\% due to an outlier false alarm rate). The
mean diarization error rate over the remaining clips was NA\%.
\textbf{In a secondary analysis only on the ACLEW data, \ldots{}
COMPLETE\ldots{} not sure the evaluation would be fair to LENA. My
understanding is that their human annotators marked all sound as TV --
whereas you only marked speech as electronic. This means that neither
the recall nor the precision can be trusted in our analysis: If we find
that 50\% of what LENA called TV was tagged as electronic speech, this
may well be true. the other 50\% was music, jingles, other TV sound. If
we say that the recall is 30\%, we don't know what the LENA-defined
recall was -- perhaps LENA did miss 70\% of what you tagged as
electronic speech, but found 100\% of the music and the other TV sounds,
so the recall might be much higher than what we say.}

\subsubsection{LENA classification accuracy: Precision and
recall}\label{lena-classification-accuracy-precision-and-recall}

\begin{verbatim}
By now, we have established that the best performance (when "far" labels such as CHF and OLF are mapped onto silence), the overall relative diarization error rate is about NA%%, due mainly to missing speech (`round(mean(py$missed.detection..,na.rm=T))`%%), with false alarms (`round(mean(py$false.alarm..,na.rm=T))`%) and confusion between talker categories (`round(mean(py$confusion..,na.rm=T))`%) constituting a relatively small proportion of errors. However, this metric may not capture what our readers are interested in, for two reasons. First, this metric gives more importance to correctly classifying segments as speech versus non-speech (False alarms + misses) than confusing talkers (confusion). Second, many LENA adopters use the system not to make decisions on the sections labeled as non-speech, but rather on sections labeled as speech, and particularly those labeled adults and key child. The metrics above do not give more importance to these two categories, and do not give us insight on the patterns of error made by the system. Looking at precision of speech categories is crucial for users who interpret LENA's estimated quantity of adult speech or key child speech, as low precision means that some of what LENA called e.g. key child was not in fact the key child, and thus it is providing overestimates. Looking at recall may be most interesting for adopters who intend to employ LENA as a first-pass annotation: the lower the recall, the more is missed by the system and thus cannot be retrieved (because the system labeled it as something else, which will not be inspected given the original filter). Recall also impacts quantity estimates, since it indicates how much was missed of that category.
\end{verbatim}

Therefore, this subsection shows confusion matrices, containing
information on precision and recall, for each key category. For this
analysis, we collapsed over all human annotations that contained overlap
between two speakers into a category called \enquote{overlap}. Please
remember that this category is not defined the same way as the LENA
overlap category. For LENA, overlap between any two categories falls
within overlap -- i.e., CHN+TV would be counted towards overlap; whereas
for us, only overlap between two talker categories (e.g., key child and
female adult) counts as overlap. (Note that neither case contemplates
overlap between two speakers of the same category as overlap.)

\begin{figure}
\centering
\includegraphics{main_document_files/figure-latex/ggprec-1.pdf}
\caption{}
\end{figure}

We start by explaining how to interpret one cell in Figure (precision):
Focus on the crossing of the human category FEM and the LENA category
FAN; when LENA tags a given frame as FAN, this corresponds to a frame
tagged as being a female adult by the human 52\% of the time. This
category, as mentioned above, is the most common speaker category in the
audio, so that over 57k frames (representing 52 of the frames tagged as
FAN by LENA) were tagged as being female adult by both the human and
LENA. The remaining 2, 0, 1, 8, 0, and 37\% of frames that LENA tagged
as FAN were actually other categories according to our human coders:
37\% were silence, 8\% were in regions of overlap between speakers or
between a speaker and an electronic voice, and 3\% were due to
confusions with other speaker tags. Inspection of the rest of the
confusion matrix shows that, other than silence, this is the most
precise LENA tag.

Precision for CHN comes in secondplace, at 39\%; thus, fewer than half
of the frames labeled as being the key child are, in fact, the key
child. The majority of the frames, LENA incorrectly tagged as being the
key child are actually silence (or rather, lack of speech) according to
the human annotator
(\texttt{round(stall\$pr{[}stall\$lena=="CHN"\ \&\ stall\$human=="SIL"{]})}\%),
with the remaining errors being due to confusion with other categories:
About 8\% of them are actually a female adult; 2\% are another child;
and 7\% are regions of overlap across speakers, according to our human
coders.

MAN and CXN score similarly, 8 and 6\% respectively, meaning that less
than a tenth of the areas LENA tagged as being these speakers actually
correspond to them. As with the key child, most errors are due to LENA
tagging silent frames as these categories. However, in this case
confusion with other speaker tags is far from negligible. In fact, the
most common speaker tag in the human annotation among the regions that
LENA tagged as being MAN were actually female adult speech
(\texttt{round(stall\$pr{[}stall\$lena=="MAN"\ \&\ stall\$human=="FEM"{]})}\%);
and, for CXN, it was not uncommon to find a CXN tag for a frame human
listeners identified as a female adult
(\texttt{round(stall\$pr{[}stall\$lena=="CXN"\ \&\ stall\$human=="FEM"{]})}\%)
or the key child
(\texttt{round(stall\$pr{[}stall\$lena=="CXN"\ \&\ stall\$human=="OCH"{]})}\%).
In a nutshell, this suggests extreme caution before undertaking any
analyses that rely on the precision of MAN and CXN, since most of what
is being tagged as such is silence or other speakers.

Another observation is that the \enquote{far} tags of the speaker
categories do tend to more frequently correspond to what humans tagged
as silence
(\texttt{round(mean(stall\$pr{[}substr(stall\$lena,3,3)=="F"\ \&\ stall\$human=="SIL"{]}))}\%)
than the \enquote{near} tags
(\texttt{round(mean(stall\$pr{[}substr(stall\$lena,3,3)=="N"\ \&\ stall\$human=="SIL"{]}))}\%),
and thus it is reasonable to exclude them from consideration. The
relatively high proportion of near LENA tags that correspond to regions
that humans labeled as silence could be partially due to the fact that
the LENA system, in order to process a daylong recording quickly, does
not make judgments on small frames independently, but rather imposes a
minimum duration for all speaker categories, padding with silence in
order to achieve it. Thus, any key child utterance that is shorter than
.6 secs will contain as much silence as needed to achieve this minimum
(and more for the other talker categories). Our system of annotation,
whereby human annotators had no access whatsoever to the LENA tags, puts
us in an ideal situation to assess the impact of this design decision,
because any annotation that starts from the LENA segmentation should
bias the human annotator to ignore such short interstitial silences to a
greater extent than if they have no access to their tags whatsoever.

\begin{verbatim}
These analyses shed light on the extent to which we can trust the LENA tags to contain what the name indicates. We now move on to recall, which indicates a complementary perspective: how much of the original annotations were captured by LENA.
\end{verbatim}

\begin{verbatim}
## FEM CHI OCH MAL OVL ELE SIL 
## 100 100 100 100 100 100 100
\end{verbatim}

\begin{figure}
\centering
\includegraphics{main_document_files/figure-latex/ggrec-1.pdf}
\caption{}
\end{figure}

\begin{verbatim}
Again, we start with an example to facilitate the interpretation of this figure: The best performance for a talker category this time is CHN: Nearly half of the original frames humans tagged as being uttered by the key child were captured by the LENA under the CHN tag. Among the remaining regions that humans labeled as being the key child, 22% was captured by LENA's CXN category and 20% by its OLN tag, with the remainder spread out across several categories. This result can be taken to suggest that an analysis pipeline that uses the LENA system to capture the key child's vocalizations by extracting only CHN regions will get nearly half of the key child's speech. Where additional human vetting is occuring in the pipeline, such researchers may consider additionally pulling out segments labeled as CXN, since this category actually contains a further 22% of the key child's speech. Moreover, as we saw above, over a third of these LENA tags corresponds to the key child, which means that human coders who are re-coding these regions could filter out the two thirds that do not.

Many colleagues also use the LENA as a first pass to capture female adult speech via their FAN label. Only 30 of the female adult speech can be captured this way. Unlike the case of the key child, missed female speech is classified into many of the other categories, and thus there may not exist an easy solution (i.e., one would have to pull out all examples of many other categories to get at least half of the original female adult). However, if the hope is to capture as much of the female speech as possible, perhaps a solution may be to also pull out OLN regions, since these capture a further 25% of the original female adult speech and, out of the OLN tags, 16% are indeed female adults (meaning that human annotators re-coding these regions need to filter out 4 out of 5 clips, on average).

For the remaining two near speaker labels (MAN, CXN), recall averaged 15%, meaning that less than a quarter of male adult and other child speech is being captured by LENA. In fact, most of these speakers' contributions are being tagged by the LENA as OLN (mean across MAN and CXN 34%) or silence (mean across MAN and CXN 7%), although the remaining sizable proportion of misses is actually distributed across many categories. 
\end{verbatim}

Finally, as with precision, the \enquote{far} categories show worse
performance than the \enquote{near} ones. It is always the case that a
higher percentage of frames is \enquote{captured} by the near rather
than the far labels. For instance, out of all frames attributed to the
key child by the human annotator, 42\% were picked up by the LENA CHN
label versus 0\% by the LENA CHF label. This result can be used to argue
why, when sampling LENA daylong files using the LENA software, users
need not take into account the \enquote{F} categories.

\subsubsection{Child Vocalization Counts (CVC)
accuracy}\label{child-vocalization-counts-cvc-accuracy}

Given the inaccuracy of far LENA tags, and in order to follow the LENA
system procedure, we only counted vocalizations attributed to CHN and
ignored those attributed to CHF. As shown in Figure (CVC), there is a
strong association between clip-level counts estimated via the LENA
system and those found in the human annotations: the Pearson correlation
between the two was r=\texttt{round(cor.cvc.all\$estimate,3)}
(p=\texttt{signif(cor.cvc.all\$p.value,3)}) when all clips were taken
into account, and r=\texttt{round(cor.cvc.noZeros\$estimate,3)}
(p=\texttt{signif(cor.cvc.noZeros\$p.value,3)}) when only clips with
some child speech (i.e., excluding clips with 0 counts in both LENA and
human annotations) were considered. This suggests that the LENA system
captures differences in terms of number of child vocalizations across
clips well.

\begin{figure}
\centering
\includegraphics{main_document_files/figure-latex/cvc-fig-1.pdf}
\caption{}
\end{figure}

However, users need more: They also interpret the absolute number of
vocalizations found by LENA. Therefore, it is important to also bear in
mind the absolute error rate and the relative error rate. The absolute
error rate tells us, given a LENA estimate, how close the actual number
may be. The relative error rate puts this number in relation to the
actual number of vocalizations tagged by the human coder. For instance,
imagine that we find that LENA errs by 10 vocalizations according to the
absolute error rate; this means that, on average across short clips like
the ones used here, the numbers by LENA would be off by 10
vocalizations. We may think this number is small; by using the relative
error rate, we can check whether it is small relative to the actual
number: An error of 10 vocalizations would seem less problematic if
there are 100 vocalizations on average (LENA would be just 10\% off)
than if there are 10 (LENA would be doubling the number of
vocalizations).

The absolute error rate ranged from -47 to 30, with a mean of -1.63 and
a median of 0. As for relative error rates, these require the number in
the denominator to be non-null. For this analysis, therefore, we need to
remove the 460 clips in which the human annotator said there were no
child vocalizations whatsoever. When we do this, the mean relative error
rate ranged from -100 to 800, with a mean of -20.17 and a median of
-44.44

\subsubsection{Conversational Turn Counts (CTC)
accuracy}\label{conversational-turn-counts-ctc-accuracy}

\begin{figure}
\centering
\includegraphics{main_document_files/figure-latex/ctc-1.pdf}
\caption{}
\end{figure}

\begin{verbatim}
Again, we only considered "near" speaker categories in the turn count, and applied the same rule the LENA does, where a turn can be from the key child to an adult or vice versa, and should happen within 5 seconds to be counted. The association between clip-level LENA and human CTC was weaker than that found for CVC:  the Pearson correlation between the two was r=`round(cor.ctc.all$estimate,3)` (p=`signif(cor.ctc.all$p.value,3)`) when all clips were taken into account, and r=`round(cor.ctc.noZeros$estimate,3)` (p=`signif(cor.ctc.noZeros$p.value,3)`)  when only clips with some child speech (i.e., excluding 322 clips with 0 counts in both LENA and human annotations) were considered. This suggests that the LENA system captures  differences in terms of number of child vocalizations across clips well. The absolute error rate ranged from -75 to 25, with a mean of -6.82 and a median of 0. As for  relative error rates, these require the number in the denominator to be non-null. For this analysis, therefore, we need to remove the 427 clips in which the human annotator said there were no child-adult or adult-child turns  whatsoever. When we do this, the mean relative error rate ranged from -100 to 366.67, with a mean of -64.64 and a median of -81.82
\end{verbatim}

\subsubsection{Adult Word Counts
accuracy}\label{adult-word-counts-accuracy}

\begin{figure}
\centering
\includegraphics{main_document_files/figure-latex/awc-1.pdf}
\caption{}
\end{figure}

One child in the SOD corpus was learning French. We have included this
child to increase power, but results without this one child are nearly
identical. The association between clip-level LENA and human AWC was
strong: the Pearson correlation between the two was
r=\texttt{round(cor.awc.all\$estimate,3)}
(p=\texttt{signif(cor.awc.all\$p.value,3)}) when all clips were taken
into account, and r=\texttt{round(cor.awc.noZeros\$estimate,3)}
(p=\texttt{signif(cor.awc.noZeros\$p.value,3)}) when only clips with
some child speech (i.e., excluding 309 clips with 0 counts in both LENA
and human annotations) were considered. This suggests that the LENA
system captures differences in terms of number of child vocalizations
across clips well. The absolute error rate ranged from Inf to -Inf, with
a mean of NA and a median of NA. As for relative error rates, these
require the number in the denominator to be non-null. For this analysis,
therefore, we need to remove the 361 clips in which the human annotator
said there were no child-adult or adult-child turns whatsoever. When we
do this, the mean relative error rate ranged from Inf to -Inf, with a
mean of NA and a median of NA

\subsubsection{Effects of age and differences across
corpora}\label{effects-of-age-and-differences-across-corpora}

The preceding sections include results that are wholesale, over all
corpora. However, we have reason to believe that performance could be
higher for the corpora collected in North America (BER, WAR, SOD) than
those collected in other English-speaking countries (L05) or non-English
speaking populations (TSI). Additionally, our age ranges are wide, and
in the case of TSI children, some of the children are older than the
oldest children in the LENA training set. To assess whether accuracy
varies as a function of corpora and child age, we fit mixed models as
follows.

\begin{verbatim}
## [1] "false.alarm.."
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: py[, dv]
##          Chisq Df Pr(>Chisq)
## cor     3.5121  4     0.4760
## age     0.0966  1     0.7560
## cor:age 0.7418  4     0.9461
## [1] "missed.detection.."
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: py[, dv]
##          Chisq Df Pr(>Chisq)
## cor     5.4996  4     0.2398
## age     0.6570  1     0.4176
## cor:age 3.0631  4     0.5473
## [1] "confusion.."
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: py[, dv]
##          Chisq Df Pr(>Chisq)
## cor     1.4210  4     0.8405
## age     0.0363  1     0.8490
## cor:age 0.7710  4     0.9423
\end{verbatim}

We predicted false alarm, miss, and confusion rates (when all
\enquote{F} categories, TV, and overlap were mapped onto silence, which
yielded the best results in Section XX) from corpus, child age, and the
interaction as fixed effects, child ID as random effect, on clips where
there was some speech according to the human annotator. We followed up
with an Analysis of Variance (type 2) to assess significance. In none of
these analyses was corpus, child age, or their interaction significant.

\begin{verbatim}
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CVC_gold
##                  Chisq Df Pr(>Chisq)    
## CVC_n         829.4374  1  < 2.2e-16 ***
## age             1.0491  1   0.305709    
## cor            14.5371  4   0.005764 ** 
## CVC_n:age       0.0031  1   0.955480    
## CVC_n:cor      18.6516  4   0.000920 ***
## age:cor         8.3860  4   0.078421 .  
## CVC_n:age:cor  15.4232  4   0.003899 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{verbatim}
## [1] "BER"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CVC_gold ~ CVC_n * age + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1000
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.7770 -0.4192 -0.2206  0.3487  5.1915 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept)  0.00    0.000   
##  Residual             44.26    6.653   
## Number of obs: 150, groups:  child, 10
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  3.93811    2.28819   1.721
## CVC_n        0.02817    0.29869   0.094
## age         -0.16420    0.19614  -0.837
## CVC_n:age    0.07904    0.02565   3.082
## 
## Correlation of Fixed Effects:
##           (Intr) CVC_n  age   
## CVC_n     -0.557              
## age       -0.957  0.534       
## CVC_n:age  0.533 -0.958 -0.559
## convergence code: 0
## boundary (singular) fit: see ?isSingular
## 
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CVC_gold
##              Chisq Df Pr(>Chisq)    
## CVC_n     113.3771  1  < 2.2e-16 ***
## age         1.1418  1   0.285278    
## CVC_n:age   9.4971  1   0.002058 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## [1] "ROW"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CVC_gold ~ CVC_n * age + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1100.9
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.7159 -0.2756 -0.1524  0.1559  3.5413 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept)  2.479   1.575   
##  Residual             84.446   9.189   
## Number of obs: 150, groups:  child, 10
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  4.06568    3.66598   1.109
## CVC_n        0.88970    0.31243   2.848
## age         -0.11036    0.17175  -0.643
## CVC_n:age    0.01128    0.01403   0.804
## 
## Correlation of Fixed Effects:
##           (Intr) CVC_n  age   
## CVC_n     -0.539              
## age       -0.956  0.492       
## CVC_n:age  0.515 -0.961 -0.511
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CVC_gold
##              Chisq Df Pr(>Chisq)    
## CVC_n     172.0008  1     <2e-16 ***
## age         0.0726  1     0.7876    
## CVC_n:age   0.6468  1     0.4213    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## [1] "SOD"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CVC_gold ~ CVC_n * age + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1109.1
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.9047 -0.4847 -0.1404  0.3426  4.6474 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept)  7.038   2.653   
##  Residual             86.926   9.323   
## Number of obs: 150, groups:  child, 10
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept) -2.56105    2.43857  -1.050
## CVC_n        1.14124    0.20555   5.552
## age          0.34207    0.16806   2.035
## CVC_n:age   -0.01315    0.01048  -1.254
## 
## Correlation of Fixed Effects:
##           (Intr) CVC_n  age   
## CVC_n     -0.478              
## age       -0.850  0.353       
## CVC_n:age  0.467 -0.836 -0.488
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CVC_gold
##             Chisq Df Pr(>Chisq)    
## CVC_n     67.3116  1  2.318e-16 ***
## age        2.6600  1     0.1029    
## CVC_n:age  1.5726  1     0.2098    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## [1] "tsi"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CVC_gold ~ CVC_n * age + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1387.3
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.4166 -0.2733 -0.2194  0.0552  4.8604 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept) 0.1557   0.3946  
##  Residual             8.8421   2.9736  
## Number of obs: 272, groups:  child, 13
## 
## Fixed effects:
##              Estimate Std. Error t value
## (Intercept)  0.798721   0.628016   1.272
## CVC_n        0.711235   0.081359   8.742
## age         -0.004027   0.017648  -0.228
## CVC_n:age    0.002223   0.002420   0.919
## 
## Correlation of Fixed Effects:
##           (Intr) CVC_n  age   
## CVC_n     -0.464              
## age       -0.925  0.434       
## CVC_n:age  0.420 -0.865 -0.483
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CVC_gold
##              Chisq Df Pr(>Chisq)    
## CVC_n     360.6574  1     <2e-16 ***
## age         0.0606  1     0.8055    
## CVC_n:age   0.8437  1     0.3584    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## [1] "WAR"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CVC_gold ~ CVC_n * age + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1083.8
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.6257 -0.2436 -0.1614  0.3904  3.2265 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept)  0.00    0.000   
##  Residual             78.71    8.872   
## Number of obs: 150, groups:  child, 10
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  0.98265    2.46135   0.399
## CVC_n        1.70718    0.25724   6.636
## age          0.13091    0.37010   0.354
## CVC_n:age   -0.06636    0.03764  -1.763
## 
## Correlation of Fixed Effects:
##           (Intr) CVC_n  age   
## CVC_n     -0.599              
## age       -0.932  0.565       
## CVC_n:age  0.577 -0.944 -0.617
## convergence code: 0
## boundary (singular) fit: see ?isSingular
## 
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CVC_gold
##              Chisq Df Pr(>Chisq)    
## CVC_n     225.5910  1    < 2e-16 ***
## age         0.8693  1    0.35115    
## CVC_n:age   3.1080  1    0.07791 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

For CVC, we fit a mixed model where CVC according to the human was
predicted from CVC according to LENA, in interaction with corpus and
age, as fixed factors; with child ID as random effect. An Analysis of
Variance (type 2) found a triple interaction, suggesting that the
predicted value of LENA with respect to human CVC depended on both the
corpus and the child age; and a two-way interaction between CVC by LENA
and corpus. To investigate these further, we fit a model where CVC
according to the human was predicted from CVC according to LENA in
interaction with age (as fixed factors, with child ID as random) within
each corpus separately. This revealed a significant interaction between
LENA CVC and age for BER (indicating that the predictive value of LENA
CVC increased with child age), whereas for the other four corpora this
interaction was not significant, nor was the main effect of age, and
only the LENA CVC emerged as a significant predictor of variance in
child vocalization counts derived from human
annotation.\href{For\%20both\%20BER\%20and\%20WAR,\%20the\%20variance\%20associated\%20to\%20the\%20child\%20ID\%20random\%20factor\%20was\%20zero.\%20This\%20suggests\%20a\%20mixed\%20model\%20was\%20not\%20necessary,\%20as\%20child\%20ID\%20is\%20not\%20explaining\%20any\%20additional\%20variance,\%20but\%20it\%20does\%20not\%20alter\%20the\%20interpretation\%20in\%20the\%20main\%20text.}{singfit}

\begin{verbatim}
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CTC_gold
##                  Chisq Df Pr(>Chisq)    
## CTC_n         320.5986  1  < 2.2e-16 ***
## age             0.0043  1  0.9474984    
## cor            23.0362  4  0.0001245 ***
## CTC_n:age       0.0841  1  0.7718559    
## CTC_n:cor      16.7594  4  0.0021525 ** 
## age:cor         3.9185  4  0.4171444    
## CTC_n:age:cor   2.4911  4  0.6462331    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{verbatim}
## [1] "BER"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CTC_gold ~ CTC_n + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1170.9
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.7480 -0.5458 -0.4878  0.6037  3.8203 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept)   0.125   0.3536 
##  Residual             145.499  12.0623 
## Number of obs: 150, groups:  child, 10
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   6.5687     1.1399   5.763
## CTC_n         1.1609     0.1566   7.411
## 
## Correlation of Fixed Effects:
##       (Intr)
## CTC_n -0.494
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CTC_gold
##        Chisq Df Pr(>Chisq)    
## CTC_n 54.924  1  1.253e-13 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## [1] "ROW"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CTC_gold ~ CTC_n + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1275.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.9053 -0.4983 -0.4112  0.3700  3.8540 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept)   4.652   2.157  
##  Residual             290.961  17.058  
## Number of obs: 150, groups:  child, 10
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   7.7528     1.7844   4.345
## CTC_n         1.6243     0.2082   7.803
## 
## Correlation of Fixed Effects:
##       (Intr)
## CTC_n -0.495
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CTC_gold
##       Chisq Df Pr(>Chisq)    
## CTC_n 60.89  1  6.035e-15 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## [1] "SOD"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CTC_gold ~ CTC_n + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1270.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.0431 -0.6513 -0.3619  0.5300  3.6738 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept)  28.79    5.366  
##  Residual             269.38   16.413  
## Number of obs: 150, groups:  child, 10
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  10.3950     2.2835   4.552
## CTC_n         0.9585     0.2152   4.455
## 
## Correlation of Fixed Effects:
##       (Intr)
## CTC_n -0.322
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CTC_gold
##        Chisq Df Pr(>Chisq)    
## CTC_n 19.843  1  8.409e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## [1] "tsi"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CTC_gold ~ CTC_n + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1495
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.1532 -0.4518 -0.4518  0.3458  4.0993 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept)  0.00    0.000   
##  Residual             14.15    3.762   
## Number of obs: 272, groups:  child, 13
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  1.69937    0.25507   6.662
## CTC_n        0.94013    0.08004  11.745
## 
## Correlation of Fixed Effects:
##       (Intr)
## CTC_n -0.448
## convergence code: 0
## boundary (singular) fit: see ?isSingular
## 
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CTC_gold
##        Chisq Df Pr(>Chisq)    
## CTC_n 137.95  1  < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## [1] "WAR"
## Linear mixed model fit by REML ['lmerMod']
## Formula: CTC_gold ~ CTC_n + (1 | child)
##    Data: cvtc
##  Subset: c(cor == thiscor)
## 
## REML criterion at convergence: 1149.1
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.3493 -0.5498 -0.4841  0.4869  2.7730 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  child    (Intercept)   0.0     0.00   
##  Residual             125.6    11.21   
## Number of obs: 150, groups:  child, 10
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)   6.1614     1.0729   5.743
## CTC_n         1.6805     0.1375  12.220
## 
## Correlation of Fixed Effects:
##       (Intr)
## CTC_n -0.522
## convergence code: 0
## boundary (singular) fit: see ?isSingular
## 
## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: CTC_gold
##        Chisq Df Pr(>Chisq)    
## CTC_n 149.33  1  < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

For CTC, we fit a mixed model where CTC according to the human was
predicted from CTC according to LENA, in interaction with corpus and
age, as fixed factors; with child ID as random effect. An Analysis of
Variance (type 2) found a two-way interaction between CTC by LENA and
corpus. To investigate this further, we fit the same regressions within
each corpus separately. These follow-up analyses revealed that CTC by
LENA was a better predictor of human-tagged CTC for WAR (estimate =
1.68, SE of estimate = 0.14, t = 12.22) and TSI (estimate = 0.94, SE of
estimate = 0.08, t = 11.74), than L05 (estimate = 1.62, SE of estimate =
0.21, t = 11.74) or SOD (estimate = 0.96, SE of estimate = 0.22, t =
4.46), and for these than for BER (estimate = 1.16, SE of estimate =
0.16, t =
7.41).\href{For\%20both\%20TSI\%20and\%20WAR,\%20the\%20variance\%20associated\%20to\%20the\%20child\%20ID\%20random\%20factor\%20was\%20zero.\%20This\%20suggests\%20a\%20mixed\%20model\%20was\%20not\%20necessary,\%20as\%20child\%20ID\%20is\%20not\%20explaining\%20any\%20additional\%20variance,\%20but\%20it\%20does\%20not\%20alter\%20the\%20interpretation\%20in\%20the\%20main\%20text.}{singfit2}

\subsection{Discussion}\label{discussion}

\subsection{Acknowledgments}\label{acknowledgments}

\newpage

\section{References}\label{references}

\setlength{\parindent}{-0.5in} \setlength{\leftskip}{0.5in}






\end{document}
